# Generated by Django 6.1.1 on 2026-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantities',
            field=models.JSONField(default=dict),
        ),
    ]
